language: node_js
node_js:
  - "20"

branches:
  only:
    - master

cache: npm

install:
  - npm ci

script:
  - npm run lint
  - npm test
  - npm run build

deploy:
  provider: script
  script: npx firebase-tools deploy --project default --token "$FIREBASE_TOKEN" --non-interactive
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
