language: node_js
node_js:
  - "20"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

install:
  - npm ci --prefix react-app

script:
  - npm run lint --prefix react-app
  - npm test --prefix react-app
  - npm run build --prefix react-app

after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
